/*
 * network_config.h
 *
 *  Created on: Sep 12, 2017
 *      Author: psammand
 */

#ifndef NETWORK_EXPORT_NETWORK_CONFIG_H_
#define NETWORK_EXPORT_NETWORK_CONFIG_H_

#define ENABLE_IPV4_UNICAST_SECURE
#define ENABLE_IPV4_MULTICAST
#define ENABLE_IPV4_MULTICAST_SECURE

#define ENABLE_IPV6_UNICAST
#define ENABLE_IPV6_UNICAST_SECURE
#define ENABLE_IPV6_MULTICAST
#define ENABLE_IPV6_MULTICAST_SECURE

#endif /* NETWORK_EXPORT_NETWORK_CONFIG_H_ */
